from odoo import api, fields, models


class G2PHouseholdRegistry(models.Model):
    _name = "g2p.household.registry"
    _description = "Household Registry"
    _inherit = "g2p.registry"
    _rec_name = "name"

    name = fields.Char(string="Household", compute="_compute_name", store=True)
    household_head_internal_record_id = fields.Char(string="Household Head Internal Record ID")
    household_head_name = fields.Char(string="Household Head Name", index=True)
    husband_dead = fields.Boolean(string="Husband Dead")
    husband_dead_date = fields.Date(string="Husband Dead Date")
    size_total = fields.Integer(string="Total Household Size")
    size_adults = fields.Integer(string="Adults")
    size_children_u5 = fields.Integer(string="Children Under 5")
    size_school_age = fields.Integer(string="School Age Children")
    size_elderly = fields.Integer(string="Elderly Members")
    number_of_female_members = fields.Integer(string="Female Members")
    number_of_male_members = fields.Integer(string="Male Members")
    tenure_status = fields.Char(string="Tenure Status")
    rooms_count = fields.Integer(string="Rooms Count")
    overcrowding_indicator = fields.Float(string="Overcrowding Indicator")
    water_source_type = fields.Char(string="Water Source Type")
    water_distance_minutes = fields.Integer(string="Water Distance Minutes")
    sanitation_type = fields.Char(string="Sanitation Type")
    lighting_source = fields.Char(string="Lighting Source")
    cooking_fuel_type = fields.Char(string="Cooking Fuel Type")
    mobile_phone_type = fields.Char(string="Mobile Phone Type")
    large_area_id = fields.Integer(string="Large Area ID")
    large_area_code = fields.Char(string="Large Area Code")
    small_area_id = fields.Integer(string="Small Area ID")
    small_area_code = fields.Char(string="Small Area Code")

    # Fields synchronized from the DR-HH registry model.
    functional_record_id = fields.Char(string="Functional Record ID", index=True)
    link_internal_record_id = fields.Char(string="Link Internal Record ID")
    record_name = fields.Char(string="Record Name", index=True)
    household_size_total = fields.Integer(string="Household Size Total")
    household_size_adults = fields.Integer(string="Household Size Adults")
    household_size_children_u5 = fields.Integer(string="Household Size Children Under 5")
    household_size_school_age = fields.Integer(string="Household Size School Age")
    household_size_elderly = fields.Integer(string="Household Size Elderly")
    elderly_member_present = fields.Boolean(string="Elderly Member Present")
    household_head_person_id = fields.Char(string="Household Head Person ID")
    headship_type = fields.Char(string="Headship Type")
    household_assets = fields.Char(string="Household Assets")
    kebele_code = fields.Char(string="Kebele Code")
    locality_ea_code = fields.Char(string="Locality Ea Code")
    address_descriptor = fields.Char(string="Address Descriptor")
    gps_latitude = fields.Float(string="GPS Latitude")
    gps_longitude = fields.Float(string="GPS Longitude")
    gps_accuracy = fields.Float(string="GPS Accuracy")
    household_id = fields.Char(string="Household ID", index=True)
    first_name = fields.Char(string="First Name", index=True)
    last_name = fields.Char(string="Last Name", index=True)
    latitude = fields.Float(string="Latitude")
    longitude = fields.Float(string="Longitude")
    phone_number = fields.Char(string="Phone Number")
    province_code = fields.Char(string="Province Code")
    province_name = fields.Char(string="Province Name")
    municipality_code = fields.Char(string="Municipality Code")
    municipality_name = fields.Char(string="Municipality Name")
    municipal_district_code = fields.Char(string="Municipal District Code")
    municipal_district_name = fields.Char(string="Municipal District Name")
    section_code = fields.Char(string="Section Code")
    section_name = fields.Char(string="Section Name")
    neighborhood_code = fields.Char(string="Neighborhood Code")
    neighborhood_name = fields.Char(string="Neighborhood Name")
    sub_neighborhood_name = fields.Char(string="Sub Neighborhood Name")
    polygon_code = fields.Char(string="Polygon Code")
    block_code = fields.Char(string="Block Code")
    dwelling_order_number = fields.Char(string="Dwelling Order Number")
    street = fields.Char(string="Street")
    dwelling_number = fields.Char(string="Dwelling Number")
    building_name = fields.Char(string="Building Name")
    apartment_number = fields.Char(string="Apartment Number")
    between_street = fields.Char(string="Between Street")
    and_street = fields.Char(string="And Street")
    street_has_public_lighting = fields.Boolean(string="Street Has Public Lighting")
    street_is_paved = fields.Boolean(string="Street Is Paved")
    dwelling_type = fields.Char(string="Dwelling Type")
    dwelling_tenure = fields.Char(string="Dwelling Tenure")
    wall_material = fields.Char(string="Wall Material")
    roof_material = fields.Char(string="Roof Material")
    floor_material = fields.Char(string="Floor Material")
    number_of_bedrooms = fields.Integer(string="Number Of Bedrooms")
    number_of_households_in_dwelling = fields.Integer(string="Number Of Households In Dwelling")
    household_number = fields.Char(string="Household Number")
    drinking_water_source = fields.Char(string="Drinking Water Source")
    days_receiving_water_per_week = fields.Integer(string="Days Receiving Water Per Week")
    lighting_type = fields.Char(string="Lighting Type")
    garbage_disposal_method = fields.Char(string="Garbage Disposal Method")
    sanitary_service = fields.Char(string="Sanitary Service")
    shares_sanitary_service = fields.Boolean(string="Shares Sanitary Service")
    main_cooking_fuel = fields.Char(string="Main Cooking Fuel")
    has_television = fields.Boolean(string="Has Television")
    has_cable_television = fields.Boolean(string="Has Cable Television")
    has_computer = fields.Boolean(string="Has Computer")
    has_computer_with_internet = fields.Boolean(string="Has Computer With Internet")
    has_tablet = fields.Boolean(string="Has Tablet")
    has_mobile_phone = fields.Boolean(string="Has Mobile Phone")
    has_smartphone = fields.Boolean(string="Has Smartphone")
    has_landline = fields.Boolean(string="Has Landline")
    has_radio = fields.Boolean(string="Has Radio")
    has_stove = fields.Boolean(string="Has Stove")
    has_microwave = fields.Boolean(string="Has Microwave")
    has_air_conditioning = fields.Boolean(string="Has Air Conditioning")
    has_refrigerator = fields.Boolean(string="Has Refrigerator")
    has_washing_machine = fields.Boolean(string="Has Washing Machine")
    has_inverter = fields.Boolean(string="Has Inverter")
    has_generator = fields.Boolean(string="Has Generator")
    has_private_car = fields.Boolean(string="Has Private Car")
    has_private_motorcycle = fields.Boolean(string="Has Private Motorcycle")
    has_car_for_hire = fields.Boolean(string="Has Car For Hire")
    has_motorcycle_for_hire = fields.Boolean(string="Has Motorcycle For Hire")
    flood_risk_river = fields.Boolean(string="Flood Risk River")
    flood_risk_stream = fields.Boolean(string="Flood Risk Stream")
    flood_risk_ravine = fields.Boolean(string="Flood Risk Ravine")
    flood_risk_lagoon = fields.Boolean(string="Flood Risk Lagoon")
    flood_risk_sea_waves = fields.Boolean(string="Flood Risk Sea Waves")
    flood_risk_heavy_rain = fields.Boolean(string="Flood Risk Heavy Rain")
    landslide_risk = fields.Boolean(string="Landslide Risk")
    drought_risk = fields.Boolean(string="Drought Risk")
    forest_fire_risk = fields.Boolean(string="Forest Fire Risk")
    strong_wind_risk = fields.Boolean(string="Strong Wind Risk")
    number_of_males = fields.Integer(string="Number Of Males")
    number_of_females = fields.Integer(string="Number Of Females")
    total_persons = fields.Integer(string="Total Persons")
    household_victim_of_crime_last_year = fields.Boolean(string="Household Victim Of Crime Last Year")
    operative_key = fields.Char(string="Operative Key")
    result = fields.Char(string="Result")
    original_source = fields.Char(string="Original Source")
    household_headship_status = fields.Char(string="Household Headship Status")
    visit_date = fields.Char(string="Visit Date")
    last_clinical_visit = fields.Date(string="Last Clinical Visit")
    last_clinical_visit_facility = fields.Selection(
        [
            ("Imperial Health Clinic", "Imperial Health Clinic"),
            ("Anatomica Dominican Republic", "Anatomica Dominican Republic"),
            ("Centro Médico Punta Cana", "Centro Médico Punta Cana"),
        ],
        string="Last Clinical Visit Facility",
    )
    household_verification = fields.Char(string="Household Verification")
    visit_date_condition = fields.Char(string="Visit Date Condition")
    municipal_district_code_num3 = fields.Integer(string="Municipal District Code Num3")
    living_conditions_index_s2_a = fields.Float(string="Living Conditions Index S2 A")
    living_conditions_basic_category_s2_a = fields.Char(string="Living Conditions Basic Category S2 A")
    years_of_education15_plus = fields.Integer(string="Years Of Education15 Plus")
    head_years_of_education = fields.Integer(string="Head Years Of Education")
    literacy_rate15_plus = fields.Float(string="Literacy Rate15 Plus")
    elderly_members_count = fields.Integer(string="Elderly Members Count")
    enrolled_or_on_vacation = fields.Boolean(string="Enrolled Or On Vacation")
    employed15_plus = fields.Boolean(string="Employed15 Plus")
    neet_youth15_to24 = fields.Boolean(string="Neet Youth15 To24")
    average_household_years_of_education = fields.Float(string="Average Household Years Of Education")
    head_education_years_s3 = fields.Integer(string="Head Education Years S3")
    average_household_education_s3 = fields.Float(string="Average Household Education S3")
    literacy_rate_household_s3 = fields.Float(string="Literacy Rate Household S3")
    elderly_members_count_s3 = fields.Integer(string="Elderly Members Count S3")
    neet_rate_s3 = fields.Float(string="Neet Rate S3")
    main_floor_material_s3 = fields.Char(string="Main Floor Material S3")
    main_wall_material_s3 = fields.Char(string="Main Wall Material S3")
    main_roof_material_s3 = fields.Char(string="Main Roof Material S3")
    water_source_s3 = fields.Char(string="Water Source S3")
    sanitary_service_s3 = fields.Char(string="Sanitary Service S3")
    lighting_type_s3 = fields.Char(string="Lighting Type S3")
    garbage_disposal_s3 = fields.Char(string="Garbage Disposal S3")
    cooking_fuel_s3 = fields.Char(string="Cooking Fuel S3")
    household_equipment_s3 = fields.Char(string="Household Equipment S3")
    overcrowding_ratio_s3 = fields.Float(string="Overcrowding Ratio S3")
    dwelling_type_s3 = fields.Char(string="Dwelling Type S3")
    household_type_s3 = fields.Char(string="Household Type S3")
    family_life_cycle_s3 = fields.Char(string="Family Life Cycle S3")
    has_computer_s3 = fields.Boolean(string="Has Computer S3")
    has_tablet_s3 = fields.Boolean(string="Has Tablet S3")
    has_landline_and_mobile_s3 = fields.Boolean(string="Has Landline And Mobile S3")
    living_conditions_index_s3 = fields.Float(string="Living Conditions Index S3")
    living_conditions_basic_category_s3 = fields.Char(string="Living Conditions Basic Category S3")
    macro_region = fields.Char(string="Macro Region")
    extreme_poverty_line_jun2024 = fields.Float(string="Extreme Poverty Line Jun2024")
    general_poverty_line_jun2024 = fields.Float(string="General Poverty Line Jun2024")
    official_income_rcno_c37_jun2024 = fields.Float(string="Official Income RCNO C37 Jun2024")
    dependency_level = fields.Char(string="Dependency Level")
    persons_in_household = fields.Integer(string="Persons In Household")
    dependent_living_alone = fields.Boolean(string="Dependent Living Alone")
    moderate_or_severe_dependency = fields.Boolean(string="Moderate Or Severe Dependency")
    count_moderate_or_severe_dependent_adults = fields.Integer(string="Count Moderate Or Severe Dependent Adults")
    households_with_moderate_or_severe_dependent_adults = fields.Boolean(string="Households With Moderate Or Severe Dependent Adults")
    households_with_multiple_dependents = fields.Boolean(string="Households With Multiple Dependents")
    children_under4 = fields.Integer(string="Children Under4")
    children_under4_with_one_dependent_adult = fields.Boolean(string="Children Under4 With One Dependent Adult")
    households_children_under4_one_dependent_adult = fields.Boolean(string="Households Children Under4 One Dependent Adult")
    children_under4_with_multiple_dependent_adults = fields.Boolean(string="Children Under4 With Multiple Dependent Adults")
    households_children_under4_multiple_dependent_adults = fields.Boolean(string="Households Children Under4 Multiple Dependent Adults")
    aggraved_burden = fields.Boolean(string="Aggraved Burden")
    structural_poverty = fields.Boolean(string="Structural Poverty")
    households_in_structural_poverty = fields.Boolean(string="Households In Structural Poverty")
    female_household_head = fields.Boolean(string="Female Household Head")
    households_with_female_head = fields.Boolean(string="Households With Female Head")
    single_household_head = fields.Boolean(string="Single Household Head")
    households_with_single_head = fields.Boolean(string="Households With Single Head")
    households_with_children_under4 = fields.Boolean(string="Households With Children Under4")
    dependent_without_care = fields.Boolean(string="Dependent Without Care")
    households_with_dependent_without_care = fields.Boolean(string="Households With Dependent Without Care")
    composite_index_normal = fields.Float(string="Composite Index Normal")
    composite_index_adjusted = fields.Float(string="Composite Index Adjusted")
    percentile_group_composite_index = fields.Float(string="Percentile Group Composite Index")
    fractional_rank_composite_index = fields.Float(string="Fractional Rank Composite Index")
    above_median = fields.Boolean(string="Above Median")
    above_percentile70 = fields.Boolean(string="Above Percentile70")
    above_percentile90 = fields.Boolean(string="Above Percentile90")
    eligible_households = fields.Boolean(string="Eligible Households")
    access_to_piped_water = fields.Boolean(string="Access To Piped Water")
    has_exclusive_toilet = fields.Boolean(string="Has Exclusive Toilet")
    poor_water_and_sanitation_access = fields.Boolean(string="Poor Water And Sanitation Access")
    ivacc3_score = fields.Float(string="IVACC3 Score")
    ivacc = fields.Float(string="IVACC")
    iih = fields.Float(string="IIH")
    pmt_score = fields.Float(string="PMT Score")


    @api.depends("household_head_name", "record_name", "internal_record_id", "link_registry_id")
    def _compute_name(self):
        for record in self:
            record.name = (
                record.household_head_name
                or record.record_name
                or record.internal_record_id
                or record.link_registry_id
                or "Household"
            )
