from odoo import fields, models


class G2PIndividualRegistry(models.Model):
    _name = "g2p.individual.registry"
    _description = "Individual Registry"
    _inherit = "g2p.registry"
    _rec_name = "full_name"

    foundational_id_masked = fields.Char(string="Foundational ID Masked")
    foundational_id_verification_status = fields.Char(string="Foundational ID Verification Status")
    identity_evidence_type = fields.Char(string="Identity Evidence Type")
    date_of_birth = fields.Date(string="Date of Birth")
    plw_status_date = fields.Date(string="PLW Status Date")
    household_internal_record_id = fields.Char(string="Household Internal Record ID", index=True)
    large_area_id = fields.Integer(string="Large Area ID")
    large_area_code = fields.Char(string="Large Area Code")
    small_area_id = fields.Integer(string="Small Area ID")
    small_area_code = fields.Char(string="Small Area Code")

    # Fields synchronized from the DR-HH registry model.
    functional_record_id = fields.Char(string="Functional Record ID", index=True)
    link_internal_record_id = fields.Char(string="Link Internal Record ID", index=True)
    record_name = fields.Char(string="Record Name", index=True)
    link_foundational_id = fields.Char(string="Link Foundational ID")
    foundational_id = fields.Char(string="Foundational ID")
    gender = fields.Selection(selection=[("male", "Male"), ("female", "Female"), ("other", "Other")], string="Gender")
    birth_date = fields.Date(string="Birth Date")
    geo_lowest_level_value_id = fields.Char(string="Geo Lowest Level Value ID")
    country_code = fields.Char(string="Country Code")
    full_name = fields.Char(string="Full Name", index=True)
    legacy_program_ids = fields.Text(string="Legacy Program Ids")
    rid = fields.Char(string="RID", index=True)
    rid_status = fields.Char(string="RID Status")
    address_descriptor = fields.Char(string="Address Descriptor")
    kebele_code = fields.Char(string="Kebele Code")
    locality_ea_code = fields.Char(string="Locality Ea Code")
    gps_latitude = fields.Float(string="GPS Latitude")
    gps_longitude = fields.Float(string="GPS Longitude")
    gps_accuracy = fields.Float(string="GPS Accuracy")
    primary_phone = fields.Char(string="Primary Phone")
    alternate_phone = fields.Char(string="Alternate Phone")
    preferred_contact_method = fields.Char(string="Preferred Contact Method")
    contact_person_name = fields.Char(string="Contact Person Name")
    estimated_age = fields.Integer(string="Estimated Age")
    age_method = fields.Char(string="Age Method")
    alias_names = fields.Text(string="Alias Names")
    citizenship_category = fields.Char(string="Citizenship Category")
    relationship_to_head = fields.Char(string="Relationship To Head")
    dependency_indicator = fields.Boolean(string="Dependency Indicator")
    residency_status = fields.Char(string="Residency Status")
    land_access = fields.Boolean(string="Land Access")
    land_size = fields.Float(string="Land Size")
    productive_assets = fields.Text(string="Productive Assets")
    primary_livelihood = fields.Char(string="Primary Livelihood")
    secondary_livelihood = fields.Char(string="Secondary Livelihood")
    employment_status = fields.Char(string="Employment Status")
    coping_strategies_index = fields.Integer(string="Coping Strategies Index")
    mobile_phone_type = fields.Char(string="Mobile Phone Type")
    disability_status = fields.Char(string="Disability Status")
    orphanhood_flag = fields.Boolean(string="Orphanhood Flag")
    chronic_illness_flag = fields.Boolean(string="Chronic Illness Flag")
    displacement_status = fields.Char(string="Displacement Status")
    pastoralist_classification = fields.Char(string="Pastoralist Classification")
    high_mobility_indicator = fields.Boolean(string="High Mobility Indicator")
    plw_status = fields.Boolean(string="Plw Status")
    plw_date = fields.Date(string="Plw Date")
    is_head = fields.Boolean(string="Is Head")
