# Part of OpenG2P. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenG2P Enderase Youth Registry",
    "category": "G2P",
    "version": "17.0.1.0.0",
    "sequence": 2,
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": [
        "g2p_social_registry",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/enderase_group_kind.xml",
        "data/enderase_registry_type_data.xml",
        "data/enderase_lookup_data.xml",
        "data/g2p.enderase.admin.region.csv",
        "data/g2p.enderase.admin.zone.csv",
        "data/g2p.enderase.admin.woreda.csv",
        "data/g2p.enderase.subcity.csv",
        "data/g2p.enderase.profession.csv",
        "data/g2p.enderase.education.level.csv",
        "data/g2p.enderase.employment.status.csv",
        "data/g2p.enderase.training.area.csv",
        "data/g2p.enderase.training.schedule.csv",
        "data/g2p.enderase.support.service.csv",
        "data/g2p.enderase.interest.area.csv",
        "data/g2p.enderase.hear.about.csv",
        "data/g2p.enderase.membership.type.csv",
        "views/enderase_registry_views.xml",
        "views/enderase_lookup_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
