{
    "name": "Enderase Theme",
    "summary": "Enderase Storyteller backend theme for Odoo",
    "description": "Applies the Enderase Storyteller visual system to Odoo backend views, sidebar, and home menu.",
    "category": "Themes/Backend",
    "version": "17.0.2.13.0",
    "sequence": 999,
    "author": "Enderase Youth Association",
    "website": "",
    "license": "LGPL-3",
    "depends": ["web"],
    "data": [
        "views/webclient_templates.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            "enderase_theme/static/src/scss/primary_variables.scss",
        ],
        "web.assets_backend": [
            "enderase_theme/static/src/scss/animations.scss",
            "enderase_theme/static/src/scss/typography.scss",
            "enderase_theme/static/src/scss/backend.scss",
            "enderase_theme/static/src/scss/views.scss",
            "enderase_theme/static/src/scss/list_view.scss",
            "enderase_theme/static/src/list_kpi/list_kpi.xml",
            "enderase_theme/static/src/list_kpi/list_kpi.js",
            "enderase_theme/static/src/list_kpi/list_toolbar.js",
            "enderase_theme/static/src/list_kpi/list_kpi.scss",
            "enderase_theme/static/src/list_kpi/list_toolbar.scss",
            "enderase_theme/static/src/scss/g2p_overrides.scss",
            "enderase_theme/static/src/js/utils.js",
            "enderase_theme/static/src/js/webclient_brand.js",
            "enderase_theme/static/src/sidebar/sidebar.xml",
            "enderase_theme/static/src/sidebar/sidebar.js",
            "enderase_theme/static/src/home_menu/home_menu.xml",
            "enderase_theme/static/src/home_menu/home_menu.js",
            "enderase_theme/static/src/home_menu/home_menu.scss",
        ],
    },
    "images": ["static/src/img/enderase-icon.png"],
    "application": False,
    "installable": True,
    "auto_install": False,
}
